# Generated by Django 4.1.5 on 2023-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Docx'), ('txt', 'Txt')], default='pdf', max_length=4),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(default='http:example.doc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
