# Generated by Django 4.1.5 on 2023-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
