# Generated by Django 4.1.5 on 2023-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sentence_content_tokenized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='encode',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
