# Generated by Django 4.1.5 on 2023-02-06 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sentence_encode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='app.document'),
        ),
    ]
