# Generated by Django 4.1.5 on 2023-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='encode',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
