# Generated by Django 4.1.5 on 2023-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sentence_encode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content_tokenized',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
