# Generated by Django 4.1.5 on 2023-02-13 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_sentence_encode_remove_sentence_is_encode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='encode',
            new_name='cross_encode',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='is_encode',
            new_name='is_cross_encode',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='is_vi_encode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vi_encode',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='acronym',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
