# Generated by Django 4.1.5 on 2023-02-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_encode_document_cross_encode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='en_encode',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_en_encode',
            field=models.BooleanField(default=False),
        ),
    ]
