# Generated by Django 4.1.5 on 2023-02-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_document_en_encode_document_is_en_encode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
