# Generated by Django 4.1.5 on 2023-02-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_document_name_alter_document_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(default='', max_length=1000, null=True),
        ),
    ]
